"""Monte-Carlo failure-event sampling for restoration experiments.

Independent of the rest of ``scare.base`` so failure scenarios can be
generated by analysis scripts without pulling in the full runtime stack.
"""

from __future__ import annotations

import random
from typing import Any

import networkx as nx
from mango_energy_environments import Failure
from monee.model.child import ExtPowerGrid, HeatGenerator, PowerGenerator, Source
from monee.model.extension import GridFormingGenerator, GridFormingSource
from monee.model.grid import PowerGrid
from monee.model.multi import (
    CHP,
    CHPHG,
    GasToPower,
    PowerToGas,
    PowerToHeat,
    PowerToHeatHG,
)

from scare.base.util import obs_capacity


def create_failures(
    monee_net: Any,
    failure_type: str = "branch",
    *,
    num_failures: int = 1,
    delay_s_max: float = 5.0,
    generator_share: float = 0.5,
    generator_carriers: tuple[str, ...] | list[str] | set[str] | None = None,
) -> list[Failure]:
    """Sample ``num_failures`` events. ``failure_type``: branch | generator | mixed
    (``generator_share`` = gen fraction) | concentrated (cluster near a load-rich node) |
    island (cut above a generation-bearing subtree so it self-anchors — the only mode
    exercising the microgrid/islanding extension; concentrated/branch strand load-only
    pockets no grid-former rescues). ``generator_carriers`` (generator/mixed) restricts
    the pool; heat/gas carry temporal storage (thermal mass / linepack) storage
    extensions buffer.
    """
    carriers = frozenset(generator_carriers) if generator_carriers else None
    if failure_type == "branch":
        return _sample_branch_failures(monee_net, num_failures, delay_s_max)
    if failure_type == "generator":
        return _sample_generator_failures(
            monee_net, num_failures, delay_s_max, carriers=carriers
        )
    if failure_type == "mixed":
        n_gen = int(round(num_failures * max(0.0, min(1.0, generator_share))))
        n_branch = num_failures - n_gen
        out = _sample_branch_failures(monee_net, n_branch, delay_s_max)
        out += _sample_generator_failures(
            monee_net, n_gen, delay_s_max, carriers=carriers
        )
        return out
    if failure_type == "concentrated":
        return _sample_concentrated_failures(monee_net, num_failures, delay_s_max)
    if failure_type == "island":
        return _sample_island_failures(monee_net, num_failures, delay_s_max)
    return []


def _sample_island_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    """Cut each power branch isolating a downstream generator-bearing subtree from the
    slack into a self-anchoring island (microgrid ext promotes generators to
    ``GridForming`` refs, so the subtree stays energised vs de-energised in the clean arm
    — the paired contrast; concentrated strands load-only pockets that cannot island).
    Cut = branch nearest the slack on the path to a generator (maximises the island);
    islands kept disjoint. Falls back to ``[]`` with no slack/generator.
    """
    roots = {
        c.node_id
        for c in monee_net.childs
        if c.active and isinstance(c.model, ExtPowerGrid)
    }
    # Match GridFormingGenerator too: apply_microgrid_islanding promotes
    # PowerGenerator to GridFormingGenerator (not a subclass) before sampling.
    gen_nodes = {
        c.node_id
        for c in monee_net.childs
        if c.active and isinstance(c.model, (PowerGenerator, GridFormingGenerator))
    }
    if not roots or not gen_nodes:
        return []

    graph = nx.Graph()
    edge_branch: dict[tuple, Any] = {}
    for b in monee_net.branches:
        if b.model.is_cp():
            continue
        try:
            node = monee_net.node_by_id(b.id[0])
        except Exception:
            continue
        if not isinstance(getattr(node, "grid", None), PowerGrid):
            continue
        u, v = b.id[0], b.id[1]
        graph.add_edge(u, v)
        edge_branch[(u, v)] = b
        edge_branch[(v, u)] = b
    if graph.number_of_edges() == 0:
        return []

    # For each power branch, the component that does NOT hold a slack after the
    # cut is the island; keep only branches whose island carries a generator.
    candidates: list[tuple[int, frozenset, Any]] = []
    for (u, v), b in list(edge_branch.items()):
        if u >= v:  # dedupe the undirected pair
            continue
        graph.remove_edge(u, v)
        comp_u = nx.node_connected_component(graph, u)
        island = (
            comp_u if not (comp_u & roots) else nx.node_connected_component(graph, v)
        )
        graph.add_edge(u, v)
        if island & roots:  # cut did not disconnect from the slack (in a loop)
            continue
        n_gen = len(island & gen_nodes)
        if n_gen == 0:
            continue
        candidates.append((n_gen, frozenset(island), b))

    if not candidates:
        return []

    # Prefer generator-rich islands; sample among the top to seed variance.
    candidates.sort(key=lambda t: (-t[0], -len(t[1])))
    top_k = max(1, len(candidates) // 3)
    pool = candidates[:top_k]
    random.shuffle(pool)

    selected: list[Any] = []
    claimed: set = set()  # nodes already inside a selected island
    for _n_gen, island, b in pool:
        if len(selected) >= num_failures:
            break
        if island & claimed:  # keep islands disjoint (avoid nested cuts)
            continue
        selected.append(b)
        claimed |= set(island)
    return [
        Failure(delay_s=random.uniform(0.0, delay_s_max), branch_ids=[b.id])
        for b in selected
    ]


def _sample_concentrated_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    """BFS from a load-rich node, cutting up to ``num_failures`` branches.
    Prefers cuts that strand load-bearing nodes for a measurable deficit.
    """
    candidates = [b for b in monee_net.branches if not b.model.is_cp()]
    if not candidates:
        return []
    by_node: dict = {}
    for b in candidates:
        for nid in (b.id[0], b.id[1]):
            by_node.setdefault(nid, []).append(b)
    load_at_node: dict = {}
    for child in monee_net.childs:
        cap = obs_capacity(dict(child.model.values))
        if cap > 0:
            load_at_node[child.node_id] = load_at_node.get(child.node_id, 0.0) + cap
    # 1-hop neighbourhood load = node load + neighbour loads.
    nbr_load: dict = {}
    for n, branches in by_node.items():
        score = load_at_node.get(n, 0.0)
        for b in branches:
            other = b.id[1] if b.id[0] == n else b.id[0]
            score += load_at_node.get(other, 0.0)
        if score > 0 and len(branches) >= 1:
            nbr_load[n] = score
    if not nbr_load:
        eligible = [n for n, bs in by_node.items() if len(bs) >= 2]
        if not eligible:
            eligible = list(by_node.keys())
        target_node = random.choice(eligible)
    else:
        # Top 25% by neighbourhood load: seed variance, still load-rich.
        ranked = sorted(nbr_load.items(), key=lambda kv: -kv[1])
        top_k = max(1, len(ranked) // 4)
        target_node = random.choice([n for n, _ in ranked[:top_k]])
    selected: list = []
    selected_ids: set = set()
    visited: set = {target_node}
    frontier: list = [target_node]
    while frontier and len(selected) < num_failures:
        next_frontier: list = []
        for node in frontier:
            incident = sorted(
                by_node.get(node, []),
                key=lambda b: (
                    -load_at_node.get(b.id[1] if b.id[0] == node else b.id[0], 0.0)
                ),
            )
            for b in incident:
                if id(b) in selected_ids:
                    continue
                if len(selected) >= num_failures:
                    break
                selected.append(b)
                selected_ids.add(id(b))
                other = b.id[1] if b.id[0] == node else b.id[0]
                if other not in visited:
                    visited.add(other)
                    next_frontier.append(other)
        frontier = next_frontier
    return [
        Failure(delay_s=random.uniform(0.0, delay_s_max), branch_ids=[b.id])
        for b in selected
    ]


def _sample_branch_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    candidates = [b for b in monee_net.branches if not b.model.is_cp()]
    selected = random.sample(candidates, min(num_failures, len(candidates)))
    return [
        Failure(delay_s=random.uniform(0.0, delay_s_max), branch_ids=[b.id])
        for b in selected
    ]


def _sample_generator_failures(
    monee_net: Any,
    num_failures: int,
    delay_s_max: float,
    *,
    carriers: frozenset[str] | None = None,
) -> list[Failure]:
    """Sample generator-class components; branch CPs via ``branch_ids``,
    childs/compounds via ``Failure.custom``. ``carriers`` (if given) keeps only
    producers of those carriers.
    """
    candidates = list(_iter_generator_candidates(monee_net))
    if carriers is not None:
        by_carrier: dict[str, list] = {}
        for kind, comp in candidates:
            car = _generator_carrier(kind, comp, monee_net)
            if car in carriers:
                by_carrier.setdefault(car, []).append((kind, comp))
        if not by_carrier:
            return []
        # Stratify: take one candidate from EACH requested carrier that exists
        # (so a scarce producer — e.g. the lone PowerToGas — is reliably failed
        # and its carrier's storage sees a genuine deficit), then fill the
        # remaining slots at random across all matched candidates.
        selected = [random.choice(group) for group in by_carrier.values()]
        chosen_ids = {id(comp) for _k, comp in selected}
        rest = [
            (kind, comp)
            for group in by_carrier.values()
            for kind, comp in group
            if id(comp) not in chosen_ids
        ]
        random.shuffle(rest)
        selected += rest[: max(0, num_failures - len(selected))]
        selected = selected[:num_failures]
    else:
        if not candidates:
            return []
        selected = random.sample(candidates, min(num_failures, len(candidates)))
    out: list[Failure] = []
    for kind, component in selected:
        if kind == "branch":
            out.append(
                Failure(
                    delay_s=random.uniform(0.0, delay_s_max),
                    branch_ids=[component.id],
                )
            )
            continue
        comp = component  # bind for the closure

        def _deactivate(net, _c=comp) -> None:
            net.deactivate(_c)

        out.append(
            Failure(
                delay_s=random.uniform(0.0, delay_s_max),
                custom=_deactivate,
                custom_id=f"{kind}:{getattr(component, 'id', repr(component))}",
            )
        )
    return out


def _iter_generator_candidates(monee_net: Any):
    """Yield ``(kind, component)`` for each deactivatable generator-class
    component; ``kind`` picks the dispatch rule in the caller.
    """
    # Include grid-forming promotions so generator failures still find targets
    # after apply_microgrid_islanding (see _sample_island_failures).
    child_classes = (
        PowerGenerator,
        HeatGenerator,
        Source,
        GridFormingGenerator,
        GridFormingSource,
    )
    compound_classes = (CHP, CHPHG, PowerToHeat)
    branch_classes = (GasToPower, PowerToGas, PowerToHeatHG)

    def _is_gas_grid(child: Any) -> bool:
        try:
            grid = monee_net.node_by_id(child.node_id).grid
        except Exception:  # noqa: BLE001
            return False
        return grid is not None and hasattr(grid, "higher_heating_value_kwh_per_kg")

    for child in monee_net.childs:
        if isinstance(child.model, child_classes):
            # Skip passive gas-feed Sources (gas_gen_share sizing-floor injections): they
            # dilute the elec/heat pools and swamp the gas group (breaking
            # extension_temporal's lone-PowerToGas targeting); gas failures stay reachable
            # via P2G CPs. Exact-type check keeps promoted GridFormingSource sampleable.
            if type(child.model) is Source and _is_gas_grid(child):
                continue
            yield ("child", child)
    for compound in getattr(monee_net, "compounds", []):
        if isinstance(compound.model, compound_classes):
            yield ("compound", compound)
    for branch in monee_net.branches:
        if isinstance(branch.model, branch_classes):
            yield ("branch", branch)


def _generator_carrier(kind: str, component: Any, monee_net: Any) -> str:
    """Carrier this component supplies (the one whose deficit its failure
    creates): GasToPower counts as electricity; gas/heat producers map to the
    carrier whose storage (linepack / thermal mass) must cover the gap.
    """
    m = getattr(component, "model", component)
    if isinstance(m, (PowerGenerator, GridFormingGenerator)):
        return "electricity"
    if isinstance(m, HeatGenerator):
        return "heat"
    if isinstance(m, (Source, GridFormingSource)):
        try:
            gname = str(
                getattr(monee_net.node_by_id(component.node_id).grid, "name", "")
            ).lower()
        except Exception:
            gname = ""
        return "water" if "water" in gname else "gas"
    if isinstance(m, (CHP, CHPHG, PowerToHeat, PowerToHeatHG)):
        return "heat"
    if isinstance(m, PowerToGas):
        return "gas"
    if isinstance(m, GasToPower):
        return "electricity"
    return "electricity"
