"""Monte-Carlo failure-event sampling for restoration experiments.

Independent of the rest of ``scare.base`` so failure scenarios can be
generated by analysis scripts without pulling in the full runtime stack.
"""

from __future__ import annotations

import random
from typing import Any

from mango_energy_environments import Failure


def create_failures(
    monee_net: Any,
    failure_type: str = "branch",
    *,
    num_failures: int = 1,
    delay_s_max: float = 5.0,
    generator_share: float = 0.5,
) -> list[Failure]:
    """Sample ``num_failures`` failure events on the network.

    ``failure_type``:

    - ``"branch"``  — non-CP branches (lines, pipes).
    - ``"generator"`` — generator-class components (childs, compounds,
      and branch-class CP plants).  Deactivation routes via
      ``net.deactivate`` for childs/compounds and ``branch_ids`` for
      branch-class CPs.
    - ``"mixed"`` — random mix; ``generator_share`` controls the gen
      fraction (rest are non-CP branches).
    - ``"concentrated"`` — pick a load-rich node and disconnect up to
      ``num_failures`` of its incident branches, creating the local
      capacity asymmetry the holonic ADMM exists to resolve.
    """
    if failure_type == "branch":
        return _sample_branch_failures(monee_net, num_failures, delay_s_max)
    if failure_type == "generator":
        return _sample_generator_failures(monee_net, num_failures, delay_s_max)
    if failure_type == "mixed":
        n_gen = int(round(num_failures * max(0.0, min(1.0, generator_share))))
        n_branch = num_failures - n_gen
        out = _sample_branch_failures(monee_net, n_branch, delay_s_max)
        out += _sample_generator_failures(monee_net, n_gen, delay_s_max)
        return out
    if failure_type == "concentrated":
        return _sample_concentrated_failures(monee_net, num_failures, delay_s_max)
    return []


def _sample_concentrated_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    """BFS from a load-rich node and disconnect up to ``num_failures``
    branches in its expanding neighbourhood.  Prefers cuts that strand
    load-bearing nodes so the failure produces a measurable per-group
    deficit (the regime where the holonic ADMM has work to do).
    """
    from scare.base.util import obs_capacity

    candidates = [b for b in monee_net.branches if not b.model.is_cp()]
    if not candidates:
        return []
    by_node: dict = {}
    for b in candidates:
        for nid in (b.id[0], b.id[1]):
            by_node.setdefault(nid, []).append(b)
    load_at_node: dict = {}
    for child in monee_net.childs:
        cap = obs_capacity(dict(child.model.values))
        if cap > 0:
            load_at_node[child.node_id] = (
                load_at_node.get(child.node_id, 0.0) + cap
            )
    # 1-hop neighbourhood load = load at node + load at neighbours.
    nbr_load: dict = {}
    for n, branches in by_node.items():
        score = load_at_node.get(n, 0.0)
        for b in branches:
            other = b.id[1] if b.id[0] == n else b.id[0]
            score += load_at_node.get(other, 0.0)
        if score > 0 and len(branches) >= 1:
            nbr_load[n] = score
    if not nbr_load:
        eligible = [n for n, bs in by_node.items() if len(bs) >= 2]
        if not eligible:
            eligible = list(by_node.keys())
        target_node = random.choice(eligible)
    else:
        # Top-25% by neighbourhood load — keeps seed-variance while
        # staying in load-rich territory.
        ranked = sorted(nbr_load.items(), key=lambda kv: -kv[1])
        top_k = max(1, len(ranked) // 4)
        target_node = random.choice([n for n, _ in ranked[:top_k]])
    selected: list = []
    selected_ids: set = set()
    visited: set = {target_node}
    frontier: list = [target_node]
    while frontier and len(selected) < num_failures:
        next_frontier: list = []
        for node in frontier:
            incident = sorted(
                by_node.get(node, []),
                key=lambda b: -load_at_node.get(
                    b.id[1] if b.id[0] == node else b.id[0], 0.0
                ),
            )
            for b in incident:
                if id(b) in selected_ids:
                    continue
                if len(selected) >= num_failures:
                    break
                selected.append(b)
                selected_ids.add(id(b))
                other = b.id[1] if b.id[0] == node else b.id[0]
                if other not in visited:
                    visited.add(other)
                    next_frontier.append(other)
        frontier = next_frontier
    return [
        Failure(delay_s=random.uniform(0.0, delay_s_max), branch_ids=[b.id])
        for b in selected
    ]


def _sample_branch_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    candidates = [b for b in monee_net.branches if not b.model.is_cp()]
    selected = random.sample(candidates, min(num_failures, len(candidates)))
    return [
        Failure(delay_s=random.uniform(0.0, delay_s_max), branch_ids=[b.id])
        for b in selected
    ]


def _sample_generator_failures(
    monee_net: Any, num_failures: int, delay_s_max: float
) -> list[Failure]:
    """Sample generator-class components; route branch-class CPs via
    ``branch_ids`` and childs/compounds via ``Failure.custom``.
    """
    candidates = list(_iter_generator_candidates(monee_net))
    if not candidates:
        return []
    selected = random.sample(candidates, min(num_failures, len(candidates)))
    out: list[Failure] = []
    for kind, component in selected:
        if kind == "branch":
            out.append(Failure(
                delay_s=random.uniform(0.0, delay_s_max),
                branch_ids=[component.id],
            ))
            continue
        comp = component  # bind for closure

        def _deactivate(net, _c=comp) -> None:
            net.deactivate(_c)

        out.append(Failure(
            delay_s=random.uniform(0.0, delay_s_max),
            custom=_deactivate,
            custom_id=f"{kind}:{getattr(component, 'id', repr(component))}",
        ))
    return out


def _iter_generator_candidates(monee_net: Any):
    """Yield ``(kind, component)`` for every deactivatable generator-class
    component.  ``kind`` ∈ {``"child"``, ``"compound"``, ``"branch"``}
    selects the dispatch rule in ``_sample_generator_failures``.
    """
    from monee.model.child import HeatGenerator, PowerGenerator, Source
    from monee.model.multi import (
        CHP,
        CHPHG,
        GasToPower,
        PowerToGas,
        PowerToHeat,
        PowerToHeatHG,
    )

    child_classes = (PowerGenerator, HeatGenerator, Source)
    compound_classes = (CHP, CHPHG, PowerToHeat)
    branch_classes = (GasToPower, PowerToGas, PowerToHeatHG)

    for child in monee_net.childs:
        if isinstance(child.model, child_classes):
            yield ("child", child)
    for compound in getattr(monee_net, "compounds", []):
        if isinstance(compound.model, compound_classes):
            yield ("compound", compound)
    for branch in monee_net.branches:
        if isinstance(branch.model, branch_classes):
            yield ("branch", branch)
